[project]
name = "mock-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=37.3.0",
    "fastapi>=0.115.12",
    "uvicorn[standard]>=0.34.2",
]
