# Generated by Django 5.2.1 on 2025-05-26 19:18

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("identidate", "identidate"),
                            ("comprovante_residencia", "comprovante_residencia"),
                        ]
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/")),
                ("arquivo_url", models.URLField(blank=True, null=True)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "credor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="credores.credor",
                    ),
                ),
            ],
        ),
    ]
