# Generated by Django 5.2.1 on 2025-05-26 19:18

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Precatorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("numero_precatorio", models.CharField(max_length=50)),
                ("valor_nominal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("foro", models.CharField(max_length=20)),
                ("data_publicacao", models.DateField(auto_now_add=True)),
                (
                    "credor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precatorio",
                        to="credores.credor",
                    ),
                ),
            ],
        ),
    ]
