# Generated by Django 5.2.1 on 2025-05-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credores", "0001_initial"),
        ("precatorios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precatorio",
            name="credor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="credores.credor"
            ),
        ),
    ]
