# Generated by Django 5.2.1 on 2025-05-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credores", "0001_initial"),
        ("precatorios", "0002_alter_precatorio_credor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precatorio",
            name="credor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precatorio",
                to="credores.credor",
            ),
        ),
    ]
