# Generated by Django 5.2.1 on 2025-05-26 19:18

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("cpf_cnpj", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
    ]
